all:
	gcc -o lab03-1 lab03-1.c -lpthread -lm
	gcc -o lab03-2 lab03-2.c -lpthread
	gcc -o lab03-3 lab03-3.c -lpthread -lm
	gcc -o lab03-4 lab03-4.c -fopenmp -lm

clean:
	rm lab03-1
	rm lab03-2
	rm lab03-3
	rm lab03-4
